version: "3.6"

services:
  mongo-1:
    image: mongo:latest
    container_name: mongo-1
    ports:
      - "30000:30000"
    command: mongod --replSet study-repliSet --port 30000

  mongo-2:
    image: mongo:latest
    container_name: mongo-2
    ports:
      - "30001:30001"
    command: mongod --replSet study-repliSet --port 30001

  mongo-3:
    image: mongo:latest
    container_name: mongo-3
    ports:
      - "30002:30002"
    command: mongod --replSet study-repliSet --port 30002
